### ISSUE TITLE
E2e test fail

### ISSUE THREAD

**Issue by atul221282** [cmichaelgraham/skeleton-navigation-typescript-vscode#6]
Running gulp e2e gives an error

following is the output
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node.exe',
1 verbose cli   'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e',
1 verbose cli   '--color=always' ]
2 info using npm@3.3.4
3 info using node@v5.4.1
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~pree2e: aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3
6 silly lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~pree2e: no script for pree2e, continuing
7 info lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3
8 verbose lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: unsafe-perm in lifecycle true
9 verbose lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\bin\node-gyp-bin;C:\Aurelia\AureliaApp\src\skeleton\node_modules.bin;.\node_modules.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\AMD APP\bin\x86_64;c:\Program Files (x86)\AMD APP\bin\x86;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\atul.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\ProgramData\chocolatey\bin;C:\Users\atul\AppData\Local\Apps\2.0\41QK4NTB.YPJ\T093CYBO.C1M\boxs..tion_4b037e62ccd024b7_0002.0005_be57ddd41911ccdf\Chocolatey\bin;C:\Program Files (x86)\nodejs\;C:\Program Files\Java\jdk1.8.0_66\bin;C:\Program Files (x86)\Skype\Phone\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\dotnet\;C:\Users\atul\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
10 verbose lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: CWD: C:\Aurelia\AureliaApp\src\skeleton
11 silly lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: Args: [ '/d /s /c', 'gulp serve e2e' ]
12 silly lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: Returned: code: 1  signal: null
13 info lifecycle aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3~e2e: Failed to exec e2e script
14 verbose stack Error: aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3 e2e: `gulp serve e2e`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\utils\lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3
16 verbose cwd C:\Aurelia\AureliaApp\src\skeleton
17 error Windows_NT 10.0.10586
18 error argv "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node.exe" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\node_modules\npm\bin\npm-cli.js" "run" "e2e" "--color=always"
19 error node v5.4.1
20 error npm  v3.3.4
21 error code ELIFECYCLE
22 error aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3 e2e: `gulp serve e2e`
22 error Exit status 1
23 error Failed at the aurelia-skeleton-navigation-typescript-netcoreapp@1.0.3 e2e script 'gulp serve e2e'.
23 error This is most likely a problem with the aurelia-skeleton-navigation-typescript-netcoreapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve e2e
23 error You can get their info via:
23 error     npm owner ls aurelia-skeleton-navigation-typescript-netcoreapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by atul221282** [comment]
Closing as no response received
